### ISSUE TITLE
Move NessAnticheat.getMinecraftVersion()

### ISSUE THREAD

**Issue by A248** [herobrine99dan/NESS-Reloaded#109]
`getMinecraftVersion()` ought to be in a different class whose single responsibility it is to detect the server version.

**Comment by herobrine99dan** [comment]
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/5dbeae14c71880bb28e49dbe845d1b2d8ad252b0 and https://github.com/herobrine99dan/NESS-Reloaded/commit/36c3ef65ab70a683cd5111a9867c85d4ddf7320f
