### ISSUE TITLE
FALSE:Trident jokbon

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#132]
**What server version are you running?**
1.16.5
**What version of NESS Reloaded are you running?**
 snapshot 2.8 / latest

**Describe the Bug**
Trident with riptide flight gives invalid server gravity.
I can't increase config values because that allows cheaters flying.

//////////RIPTIDE FLAGS///////////
--
Going up:
fly invalid client gravity SUPER RARE
fly invalid server gravity SUPER RARE
speed air
--
Going down:
speed air
--
Going sideways near ground:
FlyFalseGround
SpeedFriction
IrregularMovement
speed air
--
Riptide atack:
KillAuraNoSwing
speed air
--
Water up:
jesus highdistanceY
speed air
--
water down:
HighVarianceY
speed air
--
water ground sideways:
jesus highdistanceXZ
iregular movement
FlyFalseGround
speed air
--
above water:
jesus highdistanceY
speed air
--

**Comment by jokbon** [comment]
![2021-05-09_00 52 22](https://user-images.githubusercontent.com/29400409/117554537-fc3ae800-b060-11eb-9829-cf1008f39e59.png)
![2021-05-09_00 52 27](https://user-images.githubusercontent.com/29400409/117554538-fe04ab80-b060-11eb-91cc-161a3cae630a.png)

**Comment by jokbon** [comment]
riptide 3 was in use

**Comment by jokbon** [comment]
kill aura angle partern from trident too xd

**Comment by herobrine99dan** [comment]
Here there are more false flags: https://www.youtube.com/watch?v=ySDvF4smMi0

**Comment by herobrine99dan** [comment]
[NESS-Reloaded_2.8.0-SNAPSHOT.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/6600693/NESS-Reloaded_2.8.0-SNAPSHOT.zip)
Here there is the build that maybe fixes some of those false flags

**Comment by jokbon** [comment]
This one will be severe trident false flags:
Jesus HighVarianceY
Jesus HighDistanceXZ
Irregular movement (when riptiding inside water and on surface to a block)

**Comment by herobrine99dan** [comment]
Are the others fixed?

**Comment by jokbon** [comment]
iam not sure fix most severe ones cause each interfere with eachother um its just hard to tell

**Comment by herobrine99dan** [comment]
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/5fb8cf4022a57890e3fdff6e91763ed4a9f0450d and https://github.com/herobrine99dan/NESS-Reloaded/commit/d66403035ad06d1856634c1e276bbf2a6993f74f
