### ISSUE TITLE
FALSE:Creative fly

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#133]
**What server version are you running?**
1.16.5
**What version of NESS Reloaded are you running?**
snapshot 2.8 / latest

**Describe the Bug**
While flying if you hit block in your way you get false flag. (everytime)
Sometimes at start of flight too.

**Comment by herobrine99dan** [comment]
Possible Fix: https://github.com/herobrine99dan/NESS-Reloaded/commit/b5d09c5947a3576ebcbfaa2a2b7a0d678edefb8f

**Comment by herobrine99dan** [comment]
DevBuild: [NESS-Reloaded_2.8.0-SNAPSHOT.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/6447189/NESS-Reloaded_2.8.0-SNAPSHOT.zip)
