### ISSUE TITLE
CONFIG:Speed

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#134]
**Missing configuration for SPEED**

**Comment by herobrine99dan** [comment]
Done with https://github.com/herobrine99dan/NESS-Reloaded/commit/e7b02bea96d95440a4753d373266dc795c1669d0

**Comment by herobrine99dan** [comment]
Dev Build
[NESS-Reloaded_2.8.0-SNAPSHOT.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/6443347/NESS-Reloaded_2.8.0-SNAPSHOT.zip)

**Comment by jokbon** [comment]
speed:
    speedAirIceSpeed: 0.34  #dont work no setback nothing
    speedOnBoat: 2.787 #works
    maxNormalSpeed: 2.1 #works
    speedNearSlabs: 0.25 #dont work no setback nothing
    speedAirUnderBlock: 0.8 #dont work no setback nothing
    speedAirSlimeSpeed: 0.34 #dont work no setback nothing
    speedUnderBlock: 2.54 #works
    speedAirBaseSpeed: 0.9 #works
**Checking done**

**Comment by herobrine99dan** [comment]
speedAirIceSpeed works when you are near ice
speedNearSlabs works when you are near slabs
speedAirUnderBlock works when you have a block on top of your head
speedAirSlimeSpeed works when you are near slimes

**Comment by herobrine99dan** [comment]
The tester told me it works.
