### ISSUE TITLE
FALSE: clicking on boat = speed

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#139]
**What server version are you running?**
1.16.5
**What version of NESS Reloaded are you running?**
 snapshot 2.8 / latest

**Describe the Bug**
FALSE: clicking on boat (speed check) false positive

**Comment by herobrine99dan** [comment]
what do you mean by clicking?

**Comment by jokbon** [comment]
when u click on boat from distance
u travel wery fast to that entity
and speed gives u false flag

**Comment by herobrine99dan** [comment]
how much is the (max) distance beetween you and the boat?

**Comment by herobrine99dan** [comment]
Still searching a better fix

**Comment by herobrine99dan** [comment]
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/2e225e9076efac5ddd5275e6c297e6edbb6a6ab2
