### ISSUE TITLE
FALSE: Slime,piston upvards = vertical fly

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#140]
What server version are you running?
1.16.5
What version of NESS Reloaded are you running?
snapshot 2.8 / latest

Describe the Bug
FALSE: Slime,piston upvards = vertical fly
activating piston with slime block on top and player on slimeblock

**Comment by herobrine99dan** [comment]
can you do a video or at least tell me what vertical fly it is?

**Comment by herobrine99dan** [comment]
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/cde9267f45fd14ff19507b7bf557bbc1e57b95e4 (i've tested it locally, it should work)
