### ISSUE TITLE
FALSE: when u burning next to walls = spider

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#141]
What server version are you running?
1.16.5
What version of NESS Reloaded are you running?
snapshot 2.8 / latest

Describe the Bug
FALSE: when u burning next to walls = spider

**Comment by herobrine99dan** [comment]
Also fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/cde9267f45fd14ff19507b7bf557bbc1e57b95e4
(i tested it locally, it should work)
