### ISSUE TITLE
FALSE:FlyHighDownMotion when falling

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#142]
**What server version are you running?**
1.16.5
**What version of NESS Reloaded are you running?**
NESS 2021 JUNE 2

**Do you have some videos / screenshots?**
![2021-06-03_11 20 53](https://user-images.githubusercontent.com/29400409/120612851-49428c00-c45e-11eb-9ecc-dbfe44371813.png)

**Comment by herobrine99dan** [comment]
I decided to remove the check, it is useless. Commit: https://github.com/herobrine99dan/NESS-Reloaded/commit/c542815eb08cfcbb458cf82655d4db48a17f6aba
