### ISSUE TITLE
FALSE:FlyHighJump (block corner)

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#144]
What server version are you running?
1.16.5

What version of NESS Reloaded are you running?
2021/6/6

Describe the Bug
FALSE: FlyHighJump when on corner of block
https://cdn.discordapp.com/attachments/687030050314649695/851745158281035796/unknown_2021.06.08-11.50_1.mp4

**Comment by herobrine99dan** [comment]
[NESS-Reloaded_2.8.0-SNAPSHOT.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/6642424/NESS-Reloaded_2.8.0-SNAPSHOT.zip)
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/5d076ef047bc1585da648dff04e49152238618e1
Can you test it?

**Comment by herobrine99dan** [comment]
Fixed
