### ISSUE TITLE
FALSE:Scafold angle

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#145]
**What server version are you running?**
1.16.5

**What version of NESS Reloaded are you running?**
2021/6/6

**Describe the Bug**
FALSE:Scafold angle

https://cdn.discordapp.com/attachments/687030050314649695/851428117407203328/2021-06-07_14.51.04.png

https://cdn.discordapp.com/attachments/687030050314649695/851427020289605673/unknown_2021.06.07-14.46_1.mp4

**Comment by herobrine99dan** [comment]
[NESS-Reloaded_2.8.0-SNAPSHOT.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/6642424/NESS-Reloaded_2.8.0-SNAPSHOT.zip)
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/5d076ef047bc1585da648dff04e49152238618e1
Can you test it?

**Comment by herobrine99dan** [comment]
Fixed
