### ISSUE TITLE
NOT WORKING: no clip

### ISSUE THREAD

**Issue by jokbon** [herobrine99dan/NESS-Reloaded#147]
What server version are you running?
1.16.5

What version of NESS Reloaded are you running?
2021/6/6

Describe the Bug
NOT WORKING: no clip

**Comment by herobrine99dan** [comment]
Fixed officially with https://github.com/herobrine99dan/NESS-Reloaded/commit/63e15162ac72a1bfc27396680ac82f4f45683bf8
