### ISSUE TITLE
Sigma Speed Bypass

### ISSUE THREAD

**Issue by InfinitePower563** [herobrine99dan/NESS-Reloaded#155]
**What server version are you running?**
1.16.5
**What version of NESS Reloaded are you running?**
2.8.0-SNAPSHOT
**Describe the Bug**
Sigma5 Speed on Vanilla setting doesn't trigger NESS.

**Comment by herobrine99dan** [comment]
what are the settings? Also, are Speed, SpeedAir and SpeedAirFriction enabled in configuration?
Also are you sure you don't have bypass permissions? That speed should be normally detected.

**Comment by herobrine99dan** [comment]
Sorry little mistake

**Comment by InfinitePower563** [comment]
I had all checks enabled. I didn't have a permissions plugin, so I de-opped myself and ran the hack, which wasn't picked up when I ran the check violations command through the console.

**Comment by InfinitePower563** [comment]
The settings I used was Vanilla Speed, on 4.0 speed setting.

**Comment by herobrine99dan** [comment]
> I had all checks enabled. I didn't have a permissions plugin, so I de-opped myself and ran the hack, which wasn't picked up when I ran the check violations command through the console.

After you deopped you should rejoin. NESS Reloaded calculates bypass permissions only when you join!

**Comment by InfinitePower563** [comment]
Alright, I'll try that later.

**Comment by InfinitePower563** [comment]
I just tried it again, it now works.
