### ISSUE TITLE
bug and false positive

### ISSUE THREAD

**Issue by actester1235** [herobrine99dan/NESS-Reloaded#2]
The bug is if you try to run this on a 1.15.2 paperspigot server it will give you a error in console and the anticheat wont work the false positive is this has nothing to do with the paperspigot error btw if your in gamemode creative and try to fly up ladders you'll false fastclimb and another false positive is if your in gamemode go up like 20 blocks then hold w and spam the shift bar to go down randomly you'll false Fly glide.
heres a link to paperspigot 1.15.2 https://papermc.io/downloads

**Comment by herobrine99dan** [comment]
I am fixing the 1.15.2 problem and all the false positives will be repaired in the next update.
