### ISSUE TITLE
Aimbot PitchPattern False Flag

### ISSUE THREAD

**Issue by notperry1234567890** [herobrine99dan/NESS-Reloaded#29]
if you have optifine just hold the zoom button down so you zoom and just look up and down and just look around and you will start to false that a ton

**Comment by herobrine99dan** [comment]
Can you do a video or send some screenshots?

**Comment by A248** [comment]
I can confirm this false positive

**Comment by herobrine99dan** [comment]
I don't know how to fix It...

**Comment by herobrine99dan** [comment]
Maybe after a month i have a fix to this problem!

**Comment by herobrine99dan** [comment]
Okay the new Aimbot GCD (before it was called PitchPattern) is better than before, it should give low false flag probability with optifine.
Anyway i will not close this for now, since Aimbot GCD needs more tests.

**Comment by herobrine99dan** [comment]
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/c3573c26aa16f4f7dd40ac664d947d1075cfe95e
