### ISSUE TITLE
NoGround False Flag

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#34]
jumping under a block will make you false flag NoGround https://streamable.com/cwa0le

**Comment by herobrine99dan** [comment]
Can you try this dev build on your server? (You should extract this file)
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4763884/NESS.zip)

**Comment by herobrine99dan** [comment]
sorry,i've closed this issue.

**Comment by Oecher1** [comment]
doesn't false flag when i try with this dev build so guessing its fixed
