### ISSUE TITLE
FastClick AimbotPattern Jesus And BadPackets False Flag

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#39]
I show how to do the false flags in the video https://streamable.com/s5xwdb

**Comment by herobrine99dan** [comment]
I've fixed Aimbot and BadPackets, now i'm fixing Jesus

**Comment by herobrine99dan** [comment]
Are you testing with the latest version?

**Comment by herobrine99dan** [comment]
I've Fixed the FastClick False positive, now i can close this issue
