### ISSUE TITLE
Jesus False Flag

### ISSUE THREAD

**Issue by actester1235** [herobrine99dan/NESS-Reloaded#4]
(this was on version 1.12.2 but it doesn't matter as long as theres elytra)
If you have elytra jump and glide into water then use fireworks to go faster in the water in like a ocean you will false Jesus WaterSpeed.

**Comment by herobrine99dan** [comment]
Are you using the latest version?

**Comment by actester1235** [comment]
> Are you using the latest version?

yes im using 1.8 version of ness

**Comment by herobrine99dan** [comment]
Hey please, test developer build. Say to me if i have fixed some false positive
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493239/NESS.zip)

**Comment by actester1235** [comment]
> Hey please, test developer build. Say to me if i have fixed some false positive
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493239/NESS.zip)

this jesus false is fixed
