### ISSUE TITLE
kick message change

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#42]
instead of Please Do not use Cheats! If you think this is an error, contact a staffer the last part isn't good it should be Please Do not use Cheats! If you think this is an error, contact staff.

**Comment by herobrine99dan** [comment]
You can change this message on config!

**Comment by herobrine99dan** [comment]
But okay, i will fix it

**Comment by herobrine99dan** [comment]
Fixed

**Comment by Oecher1** [comment]
> Fixed

i meant by it should be the default message

**Comment by herobrine99dan** [comment]
Yes, i've fixed the configuration message
