### ISSUE TITLE
Suggestion For aimbot pitch pattern

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#46]
not a bug but i recommend only making the player flag aimbot pitch pattern when there hitting entities instead of always cause i was flying around on my elytra and i started flagging aimbot pitch pattern and it false flags a ton for no reasons anyway so i recommend only making it flag when you hit entities to stop the false flags sense i sometimes afk and i even flag it

**Comment by herobrine99dan** [comment]
I'm making a new Aimbot Pitch Pattern check, but anyway no, i can't make this.
The Aimbot PitchPattern, you don't know maybe, but it detects also Scaffold, Nuker, Aimbot, Killaura, and other cheats.

**Comment by herobrine99dan** [comment]
I can close this issue since Aimbot Pitch Pattern (it will be Aimbot GCD) was rewrited.
Now it is doesn't have so many false flags (i hope) and it will work. I've tested with optifine, i had low false flag probability.
