### ISSUE TITLE
new error in 2.2 version :/

### ISSUE THREAD

**Issue by Oecher1** [herobrine99dan/NESS-Reloaded#55]
**What server version are you running?**
1.8.8
**What version of NESS Reloaded are you running?**
2.2
**Describe the Bug**
after updating new version yet again new errors ugh also this happens when i move
**Do you have some videos / screenshots?**
no
**If it is an error, do you have logs?**
https://hastebin.com/vukeleseco.bash

**Comment by herobrine99dan** [comment]
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5144973/NESS.zip)
Do you get this error with this new build?

**Comment by Oecher1** [comment]
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/5144973/NESS.zip)
> Do you get this error with this new build?

no and sorry for the late response i fell asleep
