### ISSUE TITLE
Omni Sprint False Flag

### ISSUE THREAD

**Issue by actester1235** [herobrine99dan/NESS-Reloaded#7]
If you have a mod like toggle sprint or just hold down your sprint key and spam w and s you will false Omni Sprint a lot and if your in gamemode creative you false it a lot easier and faster.

**Comment by herobrine99dan** [comment]
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493258/NESS.zip)
Hey please i have two module with the same name, i edited the name of the second module, please now test this build and say what module it is

**Comment by actester1235** [comment]
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493258/NESS.zip)
> Hey please i have two module with the same name, i edited the name of the second module, please now test this build and say what module it is

it says (Omni)! VL 200 [Sprint]

**Comment by herobrine99dan** [comment]
[NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493324/NESS.zip)
Hey, please can you test this build?

**Comment by actester1235** [comment]
> [NESS.zip](https://github.com/herobrine99dan/NESS-Reloaded/files/4493324/NESS.zip)
> Hey, please can you test this build?

seems to be fixed
