### ISSUE TITLE
Killaura selfhurt will false flag

### ISSUE THREAD

**Issue by InfinitePower563** [herobrine99dan/NESS-Reloaded#72]
If people hit themselves with a bow or accidentally splash the wrong potion on themselves, it will trigger selfhurt.

**Comment by herobrine99dan** [comment]
Fixed with the last commit, anyway for now we are recoding some small things so you have to wait before the next release.

**Comment by InfinitePower563** [comment]
Ok!

**Comment by A248** [comment]
We'll leave it open for tracking until the PR is merged into master

**Comment by herobrine99dan** [comment]
Okay, i've tested and this false flag seems to be fixed, anyway i will leave this issue open until we don't merge.
If you have other false flags you can report them so we can fix them

**Comment by A248** [comment]
Was fixed by https://github.com/herobrine99dan/NESS-Reloaded/pull/71/commits/644ebe4174cdd3c8ad7f8e7b5ebf4bbac4d1461a for reference

**Comment by herobrine99dan** [comment]
Okay, since we have merged, i can close this issue.
I think this week i will release an update if my Computer doesn't give problems
